### ISSUE TITLE
container is in restarting state 

### ISSUE THREAD

**Issue by achyuth-111** [getsentry/onpremise#1036]
### Environment

self-hosted (`onpremise` deployment)

### Steps to Reproduce

Installed the sentry with latest code but one container with  getsentry/relay:nightly image is in restarting state (Name:sentry_onpremise_relay_1). Tried to kill the container and restarted it but stuck at restarting state.... any suggestions will be helpful.

### Expected Result

container should be up and running (all the containers are up and running except this container)

### Actual Result

failing the container [
![image](https://user-images.githubusercontent.com/75174613/125724062-75b3710c-02ae-48a8-a9c8-8675dde9f0e7.png)
](url)

**Comment by chadwhitacre** [comment]
Did you investigate the logs for the relay container? What did you find?

Also what version specifically are you running?

**Comment by achyuth-111** [comment]
@chadwhitacre since the container is in restarting state I can't log in to that particular container but here are the log that I found

Error response from daemon: Container 5a7ef153edfacb04e8f92247e3517cdd9b1b20c690daadbd66141072a5108a9c is restarting, wait until the container is running
[]$ docker logs --tail 50 --follow --timestamps 5a7ef153edfa
2021-07-15T19:50:40.634220735Z error: could not open config file (file /work/.relay/config.yml)
2021-07-15T19:50:40.634363803Z caused by: No such file or directory (os error 2)
2021-07-15T19:51:41.884959699Z error: could not open config file (file /work/.relay/config.yml)

Since I cant log in to the sentry UI I have no idea which version we are using and is there any way we can find the version without login to the sentry UI

**Comment by chadwhitacre** [comment]
> Since I cant log in to the sentry UI I have no idea which version we are using and is there any way we can find the version without login to the sentry UI

If you downloaded a tarball the filename should have a version in it. If you git cloned then `git log --tags` might help, or `git rev-parse HEAD` would at least give the SHA.

> `2021-07-15T19:50:40.634220735Z error: could not open config file (file /work/.relay/config.yml)`

Looks like your relay config is broken?

Is this a clean install or are you upgrading?

CI is clean and I couldn't repro locally with a clean install:

1. `git clone git@github.com:getsentry/onpremise.git`
    1. `git rev-parse HEAD` &rarr; `34812ce837b29f6ff204638b7fd24caeaddb411c`
1. `cd onpremise`
1. `./reset.sh`
1. `./install.sh`
1. `docker compose up -d`
1. `docker stats`:

![Screen Shot 2021-07-19 at 2 30 45 PM](https://user-images.githubusercontent.com/134455/126209345-97027789-6ba3-484d-84e8-f8a2e3560e2d.png)

We need to find the delta between your env and CI/mine in order to pin down any bug here. So far this seems like a local config issue on your end.

**Comment by achyuth-111** [comment]
@chadwhitacre thank you so much
**current version** ****  (git rev-parse HEAD------->64aec777ceb47a151fefe428df5d351fb434d14d ) 
The relay and all the containers are stable now but failing to login to the UI part. Showing below error 
![image](https://user-images.githubusercontent.com/75174613/126218736-937eb297-ad71-45ea-94b4-4a7f359cd274.png)
 
any suggestion on this will helps me a lot.

**Comment by chadwhitacre** [comment]
> The relay and all the containers are stable now but failing to login to the UI part.

Closing here, let's pick up with #1037.
