### ISSUE TITLE
Improper Use of Word "Premise"

### ISSUE THREAD

**Issue by mayt017** [getsentry/onpremise#152]
The incorrect english word is being used in the title of this project as well as the sentry.io documentation. Below is the definition of the word "premise" (the word being improperly used) as well as the word "premises" (of which is the proper word).

**Premise** 
_Noun_
- a previous statement or proposition from which another is inferred or follows as a conclusion.

_Verb_
- base an argument, theory, or undertaking on.

**Premises**
_Noun_
- a house or building, together with its land and outbuildings, occupied by a business or considered in an official context.

**Comment by dcramer** [comment]
We decided we didn't like the word 'premises', so we used 'premise' as its accepted English.

I didn't read this article, but the title effectively speaks to our reasoning:

https://www.adamfowlerit.com/2017/04/premise-vs-premises-cares/

**Comment by mayt017** [comment]
You shouldn't take randomly submitted issues for granite. Obviously you can dismiss this ticket irregardless of what I have to say, but as a potential customer shopping around for products, proper grammer and spelling is important when choosing a product. Oh well, I will just be sipping on my expresso over here.

**Comment by mayt017** [comment]
I would say that while you are right, there is a significant number of people of whom understand the intent behind "on premise" (because of how widely accepted this English mistake is), the biggest reason to invest in making this change is Conway's law. If flaws in the communication language are permitted, the systems created by that environment are doomed to also be flawed.

**Comment by davidbrazilparker** [comment]
@mayt017 +1 to this. Also people with non native English language skills may get confused by common mistakes accepted as normal.

**Comment by dcramer** [comment]
My personal opinion is that if words are confusing or often misused, then maybe they should change. We still can't even agree on how to pronounce 'gif', or whether the Oxford Comma is correct or not. 

I'm not saying you're wrong in that it should be spelled on-premises, but changing it is work, work that we don't really benefit from (whether we agree with it or not), and not something we're looking to do.  I am happy to note (in our docs) that we explicitly spell it wrong (at least per any formal definition), so that people understand the origins of the word.

I'm hoping you wouldn't make software decisions on that, but to each their own. For the most part Sentry isn't flawed, but sometimes being flawed is ok.
