### ISSUE TITLE
Is there a k8s version?

### ISSUE THREAD

**Issue by Python8023** [getsentry/onpremise#169]
Is there a k8s version?

**Comment by mattrobenolt** [comment]
This can be run in k8s, but no, there's no all encompassing kubernetes config files for running Sentry.

**Comment by ledroide** [comment]
> Is there a k8s version?

Is someone here working on a Kubernetes port of this repository ?
I am currently trying, but I'm facing too many issues.
It looks like some data is missing.

**Comment by BYK** [comment]
There's a helm chart maintained by a community member: https://github.com/helm/charts/tree/master/stable/sentry

**Comment by ledroide** [comment]
Thanks @BYK. I already found this chart, but I was surprised not find all sentry components - compared to this _compose_ implementation.
For instance, zookeeper, kafka, memcached, clickhouse, smtp, snuba, symbolicator, and other components, are not in the chart.
Maybe because many components are useless, or maybe because they are not converted yet to chart, I couldn't say.

**Comment by BYK** [comment]
@ledroide - Ah, right. The reason is the helm chart for being Sentry 9.1 and not 10. Those additional services are definitely needed and I'm sure they'll port this repo some time soon.
