### ISSUE TITLE
docker-compose error using supplied "generate-secret-key" value

### ISSUE THREAD

**Issue by blakev** [getsentry/onpremise#26]
It didn't like something about the web container's generated key:

```
[blake@desktop sentry-onpremise] $ docker-compose run --rm web upgrade
ERROR: Invalid interpolation format for "environment" option in service "base": "1&2k$%w@kgi53#%ay$mgp=+c$0&_w^*9=r-ao5@59m5$6-lcm#"
```

`docker-compose` uses `$` as an escape character, https://github.com/docker/compose/issues/2507

**Comment by mattrobenolt** [comment]
See also https://github.com/getsentry/onpremise/issues/23 and read comment. Still under the assumption that this isn't behavior that I'd change in Sentry itself since it's more of a bug with Docker Compose imo. You can use any method to generate a secret key you'd like, it just needs to be a random string of some reasonable length.
