### ISSUE TITLE
[Errno 111] Connection refused - SMTP

### ISSUE THREAD

**Issue by karlhendrik** [getsentry/onpremise#294]
I'm trying to connect SMTP with my Office365 service, but it keep throwing following error.

`
[Errno 111] Connection refused`

What i have tried so far?

Tried with Mailgun service keeps throwing same error. Both services recommend using 587 port, tried with 25 same story. Turned TLS off and on..nothing

Here is my config:

```
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'smtp.mailgun.org'
mail.port: 587
mail.username: 'username'
mail.password: 'password '
mail.use-tls: true
# The email address to send on behalf of
mail.from: 'sentry@my.domain'
```

**Comment by mattrobenolt** [comment]
You might be on a provider or some setup that blocks those outbound ports. It’s pretty common to avoid mail abuse. 

Google (GCP) for example blocks port 25. Usually services like Mailgun provide alternative ports to connect to to work around this.

**Comment by McSneaky** [comment]
I'll leave my 2c of debugging it. Since it might help someone.

Using Amazon EC2 all required ports seemed to be open and working since telnet connection is working good on all 3 ports (25, 465 and 587) to Mailgun.

But I never got port 465 working with TLS for some reason, port 587 without TLS works fine tho.
Also had to run `./install.sh` after doing changes in `sentry/config.yml` file

After that I started to get new error, something related to connection timeout.
In `sentry/sentry.conf.py` add those lines at the start of file (from http://blog.e-shell.org/323):
```python
# Set the default socket timeout to a value that prevents connections
# to our SMTP server from timing out, due to sendmail's greeting pause
# feature.
import socket
socket.setdefaulttimeout(10)
```

Will do some more testing to get TLS working on some future date
