### ISSUE TITLE
docker-compose.yml: Specify specific versions instead of using latest

### ISSUE THREAD

**Issue by stumbaumr** [getsentry/onpremise#378]
I am having a problem since three days with my onpremise installation and try to revert to a working state. Since you use "latest" docker containers for some components this is really hard.

Can you please release only fixed working versions in your docker-compose.yml.

Also I would prefer to include the configuration as a volume instead of building it into the sentry containers with each docker-compose up run. You are currently not using docker containers as they should be.

**Comment by BYK** [comment]
>I am having a problem since three days with my onpremise installation and try to revert to a working state.

Is this because of a broken release on our end or something else?

>Can you please release only fixed working versions in your docker-compose.yml.

We are not planning to do this to encourage people to use the most recent and available version of all our services. You are free to pin any version you want from https://hub.docker.com/r/getsentry/sentry/tags and other services. All services publish each commit SHA (long and short form) as a usable tag.

>Also I would prefer to include the configuration as a volume instead of building it into the sentry containers with each docker-compose up run.

We are considering this. The main reason for the built image is the `requirements.txt` file for adding plugins easily. I guess we can drop this and mount the configuration from the folder after that or just separate them. Feel free to file a new issue for this but I think there is already one open.

>You are currently not using docker containers as they should be.

I think this is debatable and not a productive way to find a mutual solution so I'd prefer if you can keep the issues to the point.
