### ISSUE TITLE
Documentation is gone?

### ISSUE THREAD

**Issue by Wombarly** [getsentry/onpremise#492]
I'm trying to figure out how to setup everything for running Sentry On Premise but besides the README.md in this repo (which is pretty lackluster) all documentation is gone? 

For example `sentry.conf.example.py` file links to [a documentation page](https://docs.getsentry.com/on-premise/server/queue/) which just redirects here. The installation guide link on your [Community forum](https://forum.sentry.io/t/about-the-on-premise-category/18
) also just redirects here.

I can't find any information on what database is required or redis, etc. (I see mentions of Kafka in the issues?)

~Are you guys planning on deprecating On Premise support? Seems like it with the removal of all documentation about it on your website.~

**Comment by Self-Perfection** [comment]
Found new home of documentation: https://develop.sentry.dev/config/
Redirection is incorrect indeed.

**Comment by Wombarly** [comment]
I suppose that helps out with the configuration part. But it still doesn't properly document any of services that Sentry depends on.

I'm seeing stuff like kafka, zookeeper, clickhouse, postgres, memcached in the docker compose file. What if you got preexisting own HA clusters running for those? No info on how sentry interacts with them, what kind of permissions are required for least privilege, etc.

**Comment by BYK** [comment]
@Wombarly, sorry for the confusion we are in the middle of a documentation refactor and pruning (for old/obsolete stuff) and we had some hiccups. Pinged @dcramer who's working on this at the moment.

>Are you guys planning on deprecating On Premise support? Seems like it with the removal of all documentation about it on your website.

Definitely not! As mentioned above, we are just overhauling the docs and we are committed to keeping the on-premise support. That said the support would be mainly through this repo which provides a working blueprint, rather than long prose how things work together.

>I suppose that helps out with the configuration part. But it still doesn't properly document any of services that Sentry depends on.

We have been receiving requests around how Sentry and its surrounding services work together and we are hoping to get something out related to this in the coming months.

>I'm seeing stuff like kafka, zookeeper, clickhouse, postgres, memcached in the docker compose file. What if you got your own preexisting HA clusters running for those? No info on how sentry interacts with them, what kind of permissions are required for least privilege, etc.

We provide all the configurations for these and the `docker-compose.yml` file documents the inter-dependencies. Not sure what else you would like us to document as I think the information in the repo is applicable to self-hosted HA clusters too.

>I love the product, and am using the Hosted version. I just prefer running stuff on my own hardware.

Glad to hear that! If you ever get bored of that, you know where to find us 😉  (also if you are not bored and want to keep tinkering, you are always welcome over at https://forum.sentry.io or here in the repo).

**Comment by BYK** [comment]
@Self-Perfection thanks a lot for helping @Wombarly out quickly!

**Comment by Wombarly** [comment]
> Definitely not! As mentioned above, we are just overhauling the docs and we are committed to keeping the on-premise support. That said the support would be mainly through this repo which provides a working blueprint, rather than long prose how things work together.

Good to know! would've been a shame, I might have been a bit too pessimistic there.

> We provide all the configurations for these and the `docker-compose.yml` file documents the inter-dependencies. Not sure what else you would like us to document as I think the information in the repo is applicable to self-hosted HA clusters too.

I think the plans you have for documenting the surrounding services should include where to configure them within sentry, in a way that the docker compose file isn't really needed to be read to be able to set it up.

**Comment by BYK** [comment]
>I think the plans you have for documenting the surrounding services should include where to configure them within sentry, in a way that the docker compose file isn't really needed to be read to be able to set it up.

The problem with that is docs getting out of sync with reality, that's why we opted for this method for now as YAML is not the worst format to read (compared to XML or JSON). We may look into auto generating some parts in the futurue.
