### ISSUE TITLE
onpremise getting un-maintainable?

### ISSUE THREAD

**Issue by max-wittig** [getsentry/onpremise#987]
### Summary

I'm not sure, but this repo is just a bunch a shell scripts, which is kinda scary and maybe not maintainable in the long run.
Sentry is a very complex piece of software.

Are there any plans to transition to a Kubernetes approach or to directly support this project?: https://github.com/sentry-kubernetes/charts

What we are currently doing is comparing all the commits from this repo and manually adjusting the changes in our Ansible setup. (We need reproducibility, we cannot just rely on docker volumes and an `install.sh` script).

### Motivation

Current setup is only ment for PoC or a playground installation of Sentry onpremise (which is okay), but for a production setting we e.g. don't want to use docker volumes, but mount a real data volume into the containers instead etc...

### Additional Context

Could this project be supported instead?
https://github.com/sentry-kubernetes/charts

/cc @dlouzan

**Comment by BYK** [comment]
>which is kinda scary and maybe not maintainable in the long run

Is this FUD or your own perspective on matters as we have been using this setup for almost 2 years now. Not sure how long is your "long run" definition.

>Are there any plans to transition to a Kubernetes approach or to directly support this project?: sentry-kubernetes/charts

No plans for that in the foreseeable future.

>Current setup is only meant for PoC or a playground installation of Sentry onpremise (which is okay)

This is the intended purpose of the repo. It also serves as a blueprint for more advanced setups like the ones you refer to.

>but for a production setting we e.g. don't want to use docker volumes, but mount a real data volume into the containers instead etc...

I mean, if you need production capacity, you know our default answer is [sentry.io](https://sentry.io) 🙂 Is this repo making it hard to adjust to your needs, that would be my main concern. And if it is, what would be your suggestions to make it better without complicating it with Kubernetes or any other technology.

**Comment by max-wittig** [comment]
Thanks for the answers @BYK. So we will propably go to the Kubernetes setup. Sentry.io is not an option for us. We cannot send internal data to the Internet.

**Comment by max-wittig** [comment]
@BYK Wasn't ment as an offense or FOD. Just genuine interest for the direction of onpremiose, as we've noticed that this project is getting more and more complex and we're having trouble to replicate the changes into our own setup.

**Comment by BYK** [comment]
@max-wittig 

>We cannot send internal data to the Internet.

This may be applicable to you if you are interested: https://docs.sentry.io/product/relay/, especially PII scrubbing and enterprise domain management parts.

>Wasn't ment as an offense or FOD. Just genuine interest for the direction of onpremise, as we've noticed that this project is getting more and more complex and we're having trouble to replicate the changes into our own setup.

This is the part I want to help you as I think this is part of our responsibility and it should also help the folks maintaining the helm chart. Willing to learn how can we make this easier to integrate upstream. I know proper changelogs are on your list. We are planning to invest into this in the next quarter and also started in this repo in a basic way with #984.

What else would be useful to you?

**Comment by max-wittig** [comment]
Thanks for the offer. We prefer to also only rely on open-source (we know Sentry is not open-source, but pretty close). We're doing the same thing with GitLab, but we feel like we can contribute easier there: https://about.gitlab.com/customers/siemens/, as we also invest much more time into running that as well but also because we feel like that it's more stable for us.

We just cannot provide Sentry on the same level of quality that we provide GitLab, so it's still considered BETA internally. We have some breakage every Sentry release, which you can also see from our issues that we create, e.g. https://github.com/getsentry/sentry/issues/26134. I think it's very stable for you on SaaS, but do you think QA will improve for the self-hosted version or is this not something you want to strive for? (also understandable).

Sentry is a really useful thing and we would like to offer it to more people internally, but we sadly cannot. I'm not sure, if you can help here, because as you also confirmed, this repo is ment for PoCs and things before people switch to SaaS.

Proper changelogs would help a lot already.

**Comment by BYK** [comment]
> I think it's very stable for you on SaaS, but do you think QA will improve for the self-hosted version or is this not something you want to strive for? (also understandable).

The stability also comes from very good monitoring and agility (re deploying/retracting a version very quickly). Another reason is the setup here being a lot more simplified and "crippled" for the sake of simplicity. We use Google BigTable as the nodestore instead of Postgres for instance, which makes the whole "OMG Postgres is taking up 1TB" class of issues invisible to us. Another one is us using RabbitMQ, a "proper" task queue instead of piggybacking on Redis as a poor man's queue.

There are some more things like these that makes the self-hosted experience not great for anything but a small-scale deployment unless you are willing to tinker with it constantly which makes it even less like what we do internally.

>Sentry is a really useful thing and we would like to offer it to more people internally, but we sadly cannot. I'm not sure, if you can help here, because as you also confirmed, this repo is ment for PoCs and things before people switch to SaaS.

We try to help out folks in [the forum](https://forum.sentry.io) and then bake some of that knowledge back into [our self-hosted docs](https://develop.sentry.dev/self-hosted/troubleshooting/). We are open to improving this repo to make it easier to expand. Just saying don't expect us to turn this into k8s overnight as that's not the main focus :)

>Proper changelogs would help a lot already.

As promised, they are coming and hopefully by the end of October, we'll be shipping changelogs for the main product that are quite useful.

**Comment by max-wittig** [comment]
I guess it's rather stable, if we don't touch it. We also got a dev,stage,prod instance, so the biggest problem is the time it takes to adjust to the newer version and also the insecurities of checking all the commits individually. (`Did I miss something?`)

Our deployment wouldn't be even large scale. We currently have around 30 projects on there and the event log is already pretty busy. Most of that traffic is coming from us though (GitLab internal crashes and CSP violations). We don't really do any magic here. We just adjusted your shell scripts to be in Ansible form and take care of SE-Linux things as well. Wouldn't be worth to open-source that. It's not the prettiest thing. But maybe we can adapt the Kubernetes setup and contribute to that.

Thanks for the help @BYK 👍

**Comment by BYK** [comment]
>We just adjusted your shell scripts to be in Ansible form and take care of SE-Linux things as well.

Happy to adjust this repo to allow more automation for these tasks so you can get the new releases ready when they are out. We can even add tests to ensure we don't break this kind of stuff. Just sayin' 🙂

**Comment by dlouzan** [comment]
@BYK Just extending on Max's explanation, we are heavy upstream contributors and we'd really love to have a maintainable setup. We understand that everybody here is making a living ofc, just that our preferred approach is to be able to deploy ourselves and adapt / contribute whatever we add and fix.

We will probably explore options with the helm charts, I think that'd be a win-win for everybody: you'd get feedback on k8s setups plus a better maintained helm chart making sentry more popular, and we'd get a more tested and maintainable setup.

I do not know how the community chart currently tracks and integrates changes, I guess they do the same thing we do right now manually checking diffs? Do you have regular contact with the contributors? At least there'd be more eyes on updates 😅

**Comment by BYK** [comment]
>@BYK Just extending on Max's explanation, we are heavy upstream contributors and we'd really love to have a maintainable setup. We understand that everybody here is making a living ofc, just that our preferred approach is to be able to deploy ourselves and adapt / contribute whatever we add and fix.

Re, making a living. Although that's of course a concern we have (as if everybody used self-hosted we'd be out of jobs and then there wouldn't be any more Sentry), that's not the only reason. Conveniently for us, it _really_ is much easier to use the SaaS version rather than trying to scale up self-hosted. Our reasoning for this repo is as follows:

1. If you are someone who wants to try out Sentry as a PoC or just play with it, without getting too involved in operations, you should easily do that and this repo is here for that.
2. If you are someone who wants to maintain a large Sentry self-hosted installation, then very likely, whatever setup we provide will need to be changed for your specific infra and needs. What you need is a blueprint to show you what connects where and then you figure out how to scale those pieces out with some help from the docs.

This repo is supposed to serve this second goal too and I feel like that's where we are falling a bit short. We'd love to fix that but without your contributions (like these issues), it is impossible to see where the gaps are.

Makes sense?

**Comment by dlouzan** [comment]
@BYK Makes sense, and you are right that point number 2 is not really covered. For a PoC, this works, but in the long run for a moderately sized setup it doesn't, or at leat that's not our experience.

I'm not saying that a chart will solve all issues, but it's at least a way to have a *standardized* deployment that can be made configurable via templating, and deployed automatically for testing. There's other approaches, such as ansible playbooks or chef templates, or whatever other automation tooling. The thing is, as Max pointed out above, this is more of an an assorted collection of bash scripts, which doesn't make easy to track changes, nor to make it customizable.
